### ISSUE TITLE
New release for 1.0

### ISSUE THREAD

**Issue by staticfloat** [timholy/ProgressMeter.jl#106]
Hey @timholy, can you tag a new release for v1.0 please?  Amazingly enough, there are 102 recursive dependencies on this package, so this humble package is high on our list of things to get working for 1.0.  :)

**Comment by garrison** [comment]
I [was hoping to let @timholy do it](https://github.com/timholy/ProgressMeter.jl/pull/103#issuecomment-411730212), but while he has been active on github the last few days, it does not seem that he has been responding to notifications.  I'll plan to tag a `v0.6.0` release shortly.

**Comment by garrison** [comment]
New release -- associated pull request is at https://github.com/JuliaLang/METADATA.jl/pull/16582

**Comment by timholy** [comment]
Thanks Jim! And thanks for the ping, @staticfloat!

**Comment by omus** [comment]
Merged. This issue can be closed.
