### ISSUE TITLE
segfault with @threads

### ISSUE THREAD

**Issue by squaregoldfish** [timholy/ProgressMeter.jl#112]
Using ProgressMeter with the `@threads` functionality causes a segfault because the default print methods aren't thread safe. From what I can tell, using `Core.print` will solve the problem.

I can knock together a quick test soon if you like.

**Comment by zsunberg** [comment]
Hmmm... I'm not sure, but I think Core.print has some limitations (e.g. does it support color?).

Would it be better to just have one thread/process do the printing and then have each thread report back progress with a threadsafe mechanism similar to https://github.com/timholy/ProgressMeter.jl#tips-for-parallel-programming ?

Perhaps we should even encapsulate this in the progress meter by default, i.e. when you create a `Progress` object, it spawns another task specifically for printing and `next!` just communicates with that task.

**Comment by ianshmean** [comment]
This is now possible on master. The basic functionality should be threadsafe, although the macros don't accommodate `Threads.@threads` yet. See the readme for examples
