### ISSUE TITLE
Progress only displayed on exceptions and completed runs.

### ISSUE THREAD

**Issue by roberthoenig** [timholy/ProgressMeter.jl#117]
In Jupyter Lab:

![peek 2018-10-21 18-06](https://user-images.githubusercontent.com/7950151/47269932-36544500-d55c-11e8-8925-b93f17fd3c30.gif)

Note that the progress bar only shows up once I manually interrupt the kernel. My counter, however, is printing just fine.

**Comment by zsunberg** [comment]
Thanks for posting the issue! I don't have time to test atm, but I suspect it has to do with the fact that progress meters are written to `stderr` by default. Try adding `output=stdout` to the `Progress` arguments. If that makes a difference, we can consider whether defaults need to be changed somehow.

**Comment by roberthoenig** [comment]
Thanks! Adding `output=stdout` does the trick! In fact, `flush(stderr)` works as well.

Is there a reason why it prints to stderr in the first place? Progress doesn't seem like an error to me :->

**Comment by zsunberg** [comment]
Looks like it's for the purpose of easily piping things to other programs: https://github.com/timholy/ProgressMeter.jl/issues/60. Apparently common unix programs like curl, etc. use stderr

**Comment by zsunberg** [comment]
perhaps we should force it to flush periodically to prevent this problem?

**Comment by jlumpe** [comment]
> perhaps we should force it to flush periodically to prevent this problem?

I second this, having the same error and `flush(stderr)` solves it but does not work with `pmap()`.

**Comment by zsunberg** [comment]
Does anyone know anything about the performance effects of flush? Should we do it once every dt? Once every second? (dt would probably be easiest to implement)

**Comment by zsunberg** [comment]
I did some quick BenchmarkTools benchmarks, and it doesn't seem to make a huge difference (it takes 5.9 us to print and flush an 80 char string vs 4.5 us to just print it), so I think we should just flush every dt.
