### ISSUE TITLE
UndefVarError

### ISSUE THREAD

**Issue by juliohm** [timholy/ProgressMeter.jl#119]
In Julia v1.0 I am getting this strange error message when I try to use ProgressMeter:

```julia
using Random
using ProgressMeter

seed = 0
@showprogress 1 "Simulating..." for i=1:10
    err = true
    while err
        Random.seed!(seed)
        seed += 1
        err = false
    end
end

seed
```

I was thinking this had to do with the new hard scoping rules, but the issue is really related to ProgressMeter.jl. If I remove the `@showprogress` annotation from the loop, the code works as expected. Could you please give some help?

**Comment by timholy** [comment]
No, it is the scoping issue:
```julia

julia> using Random

julia> seed = 0
0

julia> for i=1:10
           err = true
           while err
               Random.seed!(seed)
               seed += 1
               err = false
           end
       end
ERROR: UndefVarError: seed not defined
Stacktrace:
 [1] top-level scope at ./REPL[3]:4 [inlined]
 [2] top-level scope at ./none:0

julia> seed
0
```

**Comment by juliohm** [comment]
Hi @timholy the code works fine in IJulia due to SoftGlobalScope.jl. However, when I add ProgressMeter I get the error again. Could you please reconsider the issue?

**Comment by timholy** [comment]
You might try filing this as a bug with SoftGlobalScope.

**Comment by juliohm** [comment]
Thank you Tim, will do. I thought it was specific to ProgressMeter though since the code above works fine.

**Comment by timholy** [comment]
It could be, but I don't have time to look into an interaction with SoftGlobalScope. It makes Julia a slightly different language, and since I don't use it, it's not my problem to figure this out.

**Comment by juliohm** [comment]
Makes total sense. I am also unhappy with this separation hard versus soft scoping rules. It is annoying though to not be able to have simple accumulations as before. There must be a very good reason for the change.

**Comment by juliohm** [comment]
Thanks Zack! That works like a charm. Good to hear from you!

**Comment by timholy** [comment]
Apologies, I just assumed you knew about that already and were asking to make it so you didn't need `global`. Didn't seem worth the effort, but now I understand better.

**Comment by juliohm** [comment]
Thank you Tim! I knew about `global` and was thinking if we could fix things on the side of ProgressMeter.jl as initially stated. Zack's comment however serves for this specific case and I can move forward with porting an old code to Julia v1.0. :+1: 

I will try to open an issue on SoftGlobalScope.jl anyways to see if something can be done.
