### ISSUE TITLE
feature-request: pmap with keyword arguments

### ISSUE THREAD

**Issue by natschil** [timholy/ProgressMeter.jl#122]
The following currently doesn't work:

```
using Distributed
addprocs()
@everywhere using ProgressMeter
xs = range(0,stop=1,length=200)
@everywhere f = x -> x+1
@showprogress pmap(f,xs; batch_size=10)
```

I get the error `ERROR: syntax: unexpected semicolon in tuple`. It would be really cool if ProgressMeter could deal with the `batch_size` keyword argument correctly, as for a lot of distributed applications where one would want a progress bar as there are so many items to pmap over, it doesn't make sense to have `batch_size==1`

**Comment by zsunberg** [comment]
Oh, shoot! That looks like a corner case that I forgot to account for. Unfortunately I won't be able to fix it for a few days. For an immediate workaround, does using a comma instead of a semicolon work?
