### ISSUE TITLE
Feature Request: Optional ProgressMeter

### ISSUE THREAD

**Issue by lstagner** [timholy/ProgressMeter.jl#132]
It would be nice to be able to turn off the progress meter via a keyword. Most of the time I only need the progress meter for debugging and I dont always want to modify the code to do that.

**Comment by bhvieira** [comment]
If you simply set the update times to `Inf` I think the progress bar is not printed.

```
ProgressMeter.@showprogress Inf " Test" for i in 1:10
    sleep(0.5)
end
```

So set a global or environmental variable in your code that dictates this and you're done.

**Comment by bhvieira** [comment]
See #70

**Comment by MarcMush** [comment]
the `enabled` keyword can disable a progress bar (documented in the readme)
