### ISSUE TITLE
visual feedback for `map` depends on presence of `sleep`

### ISSUE THREAD

**Issue by pfarndt** [timholy/ProgressMeter.jl#136]
I observed that in some cases I would get visual feedback only at the very end or after more than 1 minute time when looping with `map`:

```
using ProgressMeter

@showprogress map(1:1000) do i
    A = rand(10000,1000)
    sum(A)
end;
```
This loop runs for about 20 seconds and only shows the progress bar at the very end. 

However, when I dress the code with a `sleep` everything is fine
```
@showprogress map(1:1000) do i
    sleep(0.000001)
    A = rand(10000,1000)
    sum(A)
end;
```
and I get continuous feedback on the progress. 

This happens in the REPL, in Juno, and in JupyterLab. 

Note: A similar construction with a `for` loop works fine with and without the `sleep`.

<img width="721" alt="Screen Shot 2019-10-16 at 3 33 28 PM" src="https://user-images.githubusercontent.com/11805999/66954780-0c2e4980-f02f-11e9-8d75-9f7bfb31403b.png">

**Comment by zsunberg** [comment]
Ah, I think this might be my code's fault. In this case, `@showprogress` expands to a call to  `progress_map`, which creates a separate task for displaying the progress meter. I am guessing that, in this case, there is no reason for the computation task to yield to the display task unless the computation task sleeps. I don't know what the best solution is - does anyone who does a lot with coroutines know what to do?

**Comment by KristofferC** [comment]
Perhaps the macro can insert a `yield()` in the loop?

**Comment by zsunberg** [comment]
@KristofferC thanks! Yes, it doesn't seem like there is any significant downside to that.

**Comment by mirkobunse** [comment]
Hi!

The `yield()` solution should be part of the last example (and maybe others) in the README: https://github.com/timholy/ProgressMeter.jl#tips-for-parallel-programming

When I started from this example and replaced the `sleep` with something useful, I ended up trying to fix the "broken progress bar" for certainly more than an hour..

**Comment by timholy** [comment]
@mirkobunse, a PR would be welcome. Just click on the pencil icon on the README; anyone can improve docs, and if you wasted an hour on that you're the perfect person to know what needs changing.
