### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by DilumAluthge** [timholy/ProgressMeter.jl#150]
Can we make a new release?

I would make a PR to bump the version number, but there have been multiple commits since the last release, and I'm not sure if any are breaking.

If none are breaking, let me know, and I'll make a PR to bump the minor version number.

Cc: @timholy

**Comment by timholy** [comment]
I think the Jupyter behavior could be called breaking. Maybe we should discuss a little in #147.

**Comment by ianshmean** [comment]
On the current release I've been coming across the threaded deadlock issue (https://github.com/timholy/ProgressMeter.jl/issues/152) that was fixed in master by https://github.com/timholy/ProgressMeter.jl/pull/153.

Are we closer to making a release?
