### ISSUE TITLE
Example on Threads in README results in deadlocks

### ISSUE THREAD

**Issue by OkonSamuel** [timholy/ProgressMeter.jl#152]
The following example from **README** results in hanging for `n>=70` using 4 Threads
```using ProgressMeter
n = 10
p = Progress(n)
tasks = Vector{Task}(undef, n)
for i in 1:n
    tasks[i] = Threads.@spawn begin
        sleep(2*rand())
        next!(p)
    end
end
wait.(tasks)
```

**Comment by ianshmean** [comment]
I can't replicate this locally, but it might be that we should be using ReentrantLock over SpinLock. I've heard mentions that ReentrantLocks should basically always be used over SpinLocks since we added this functionality.

@OkonSamuel can you try out #153 and see if that fixes it for you?

**Comment by OkonSamuel** [comment]
@ianshmean Thanks. I'll check it out

**Comment by OkonSamuel** [comment]
I have tried it. It no longer hangs. But it affects the display of the progressmeter. I'll just put the progress meter display in a different tasks. That works for large n.

**Comment by OkonSamuel** [comment]
It now works. Thanks

**Comment by ianshmean** [comment]
Great, I'm going to re-open the issue so that it gets closed when that PR merges
