### ISSUE TITLE
Make color a kwarg in update!() (breaking change)

### ISSUE THREAD

**Issue by IanButterworth** [timholy/ProgressMeter.jl#160]
A note for inclusion in the next breaking release version.

https://github.com/timholy/ProgressMeter.jl/pull/159 adds the option to update `desc` as a kwarg in `update!()` and highlighted that `color` should probably become a kwarg.

i.e. if color was a kwarg, all of these would be valid
```julia
update!(prog, color=:blue)
update!(prog, desc="Step 2...")
update!(prog, offset=2)
```

Currently you have to provide counter to update the color. The other updates would work as above.

```julia
update!(prog, counter=prog.counter, color=:blue)
update!(prog, desc="Step 2...")
update!(prog, offset=2)
```

**Comment by MarcMush** [comment]
could this be added as a non-breaking feature? something like:
```julia
update!(p, counter=p.counter, _color=p.color; color=_color, options...)
```

it makes a lot more sense to have it as a keyword, especially for the color
