### ISSUE TITLE
MethodError using color kwarg

### ISSUE THREAD

**Issue by pdimens** [timholy/ProgressMeter.jl#165]
Using `ProgressMeter.jl` installed from `General` with `]add ProgressMeter`, I'm trying to follow the guide in the README, and attempting to construct a progress bar that is blue, and the code is written:
```julia
p = Progress(100, 1, color = :blue)
```
but it yields the error
```
ERROR: MethodError: no method matching Progress(::Int64, ::Int64, ::String, ::Int64, ::Symbol, ::Base.TTY; color=:blue)

Closest candidates are:
  Progress(::Integer, ::Real, ::AbstractString, ::Integer, ::Symbol, ::IO; offset) at /home/pdimens/.julia/packages/ProgressMeter/OUQkp/src/ProgressMeter.jl:95 got unsupported keyword argument "color"
  Progress(::Integer, ::Real, ::AbstractString, ::Integer, ::Symbol) at /home/pdimens/.julia/packages/ProgressMeter/OUQkp/src/ProgressMeter.jl:95 got unsupported keyword argument "color"
  Progress(::Integer, ::Real, ::AbstractString, ::Integer) at /home/pdimens/.julia/packages/ProgressMeter/OUQkp/src/ProgressMeter.jl:95 got unsupported keyword argument "color"
```
However, the docstring seems to also indicate the keyword can be used
```
help?> Progress
search: Progress progress_map ProgressMeter progress_pmap ProgressThresh ProgressUnknown @showprogress

  prog = Progress(n; dt=0.1, desc="Progress: ", color=:green, output=stderr, barlen=tty_width(desc),
  start=0) creates a progress meter for a task with n iterations or stages starting from start. Output
  will be generated at intervals at least dt seconds apart, and perhaps longer if each iteration takes
  longer than dt. desc is a description of the current task.
```
Is this a conflict of information between for another release, or perhaps I'm doing something wrong?

**Comment by ianshmean** [comment]
I think through the addition of new features the method structures have become a little confusing on kwargs. 
While `Progress(fileSize, 1)` is valid `Progress(fileSize, 1, color=:blue)` isn't.

You can see this from the example in the docstring. What you want should work if you provide `dt` as a kwarg:
```julia
p = Progress(100, dt=1, color = :blue)
```

There's probably a way to make things clearer, but it may be a breaking change and requires some thought
