### ISSUE TITLE
Tag 0.2

### ISSUE THREAD

**Issue by rened** [timholy/ProgressMeter.jl#17]
Hi Tim,
if possible, could you please tag a new version? especially `@showprogress` would be great to have without needing `Pkg.clone`.
Thanks!

**Comment by garrison** [comment]
I suppose the next version should [really be](http://semver.org/) `0.2.0` since it adds functionality.

**Comment by timholy** [comment]
Good god, yes!

But oops, I already tagged it as 0.1.3. There's quite a lot of new functionality, indeed. I'm not very careful about my version numbers.

**Comment by rened** [comment]
thanks!
