### ISSUE TITLE
ProgressMeter makes loops run slower

### ISSUE THREAD

**Issue by mtsch** [timholy/ProgressMeter.jl#171]
Adding a progress meter to a tight loop can make it run way slower. The problem is that the bar length is calculated on every call to `updateProgress`.

Here's an MWE:

```
using BenchmarkTools
using ProgressMeter

function prog_perf(n)
    prog = Progress(n)
    x = 0.0
    for i in 1:n
        x += rand()
        next!(prog)
    end
    return x
end

function noprog_perf(n)
    x = 0.0
    for i in 1:n
        x += rand()
    end
    return x
end

@btime prog_perf(1_000_000)
#  963.465 ms (2000457 allocations: 61.06 MiB)
@btime noprog_perf(1_000_000)
#  5.401 ms (0 allocations: 0 bytes)
```

This case is pretty extreme but I actually got in a situation where adding a progress meter increased the running time from ~5s to ~25s.

**Comment by timholy** [comment]
Oh dear, this wasn't supposed to happen. Thanks for catching it and for the fix!
