### ISSUE TITLE
Feature request/idea: use compilation time info

### ISSUE THREAD

**Issue by marius311** [timholy/ProgressMeter.jl#186]
With `@showprogress` in a standalone script, often the first step takes forever because of compilation, so the first ETA printed is orders of magnitude too large, and then it slowly adjusts over the subsequent steps. On Julia 1.6, I noticed `@time` tells you the compilation time, so this information must be accessible. It would be cool if ProgressMeter somehow factored this into the ETA estimate, such that it assumed the compilation time wouldn't have to be paid for subsequent steps, yielding a much more accurate/stable ETA.

**Comment by IanButterworth** [comment]
Fixed by https://github.com/timholy/ProgressMeter.jl/pull/195
I forgot to link this issue there. Thanks for highlighting it
