### ISSUE TITLE
README has incorrect keyword for "Optional use" example

### ISSUE THREAD

**Issue by fgasdia** [timholy/ProgressMeter.jl#187]
In the README the [Optional use of the progress meter](https://github.com/timholy/ProgressMeter.jl#optional-use-of-the-progress-meter) example uses the `disable = true` keyword argument to `Progress` to demonstrate disabling display of the progress meter. It seems like this should be `enabled = false`.

I didn't see anything in the commits that suggest this keyword is changing, but figured I'd open an issue to check before a pull request.

**Comment by timholy** [comment]
Seems like that might be a mistake. It was added recently in #185. A PR would be welcome.
