### ISSUE TITLE
Safety of `finish!`

### ISSUE THREAD

**Issue by mschauer** [timholy/ProgressMeter.jl#191]
Is `finish!` save to call on a meter, say if `next!` has already been called `n` times, or even `n+1` times? I couldn't pick that up from the docs. Is `finish!` necessary?

**Comment by lukemerrick** [comment]
Judging by the source code, `finish!` is a convenience method that just uses `update!` behind the scenes for both `Progress` and `ProgressThresh`, and by the way it uses `update!` it seems you're totally safe in the sense you mention (and also in the threadsafe sense of "safe"), and for `ProgressUnknown` there is no such concept as `n` anyhow.

If this is helpful info, maybe you can do the PR to clarify the docs for the next person?

[relevant source code](https://github.com/timholy/ProgressMeter.jl/blob/ef03315994f096025539b80e23eb19025c99407e/src/ProgressMeter.jl#L420) (excerpted below)
```Julia
"""
`finish!(prog)` indicates that all tasks have been completed.

See also `cancel`.
"""
function finish!(p::Progress; options...)
    while p.counter < p.n
        next!(p; options...)
    end
end

function finish!(p::ProgressThresh; options...)
    update!(p, p.thresh; options...)
end

function finish!(p::ProgressUnknown; options...)
    lock(p.reentrantlocker) do
        p.done = true
        updateProgress!(p; options...)
    end
end
```

**Comment by IanButterworth** [comment]
I agree that it was good before and `finish!` for `Progress` has been made IMO more efficient by https://github.com/timholy/ProgressMeter.jl/pull/198
