### ISSUE TITLE
Return statement in for loop doesn't work

### ISSUE THREAD

**Issue by davidanthoff** [timholy/ProgressMeter.jl#20]
This piece of code doesn't compile, but probably should:

````
using ProgressMeter

function test()
    @showprogress 1 for i=1:10
        return
    end
end
````

**Comment by garrison** [comment]
Does this hold true for any block that has a `return` statement?

**Comment by garrison** [comment]
Here's the actual failure once the macro is removed:

    function test()
        rv = begin
            return
        end
    end

Seems related to JuliaLang/julia#11169.

**Comment by garrison** [comment]
I believe I have a fix; just need to add some tests.  I will try to get to it later.

**Comment by timholy** [comment]
Thanks!
