### ISSUE TITLE
No output for updates with step=0

### ISSUE THREAD

**Issue by IanButterworth** [timholy/ProgressMeter.jl#201]
Reported by @vancleve here https://github.com/timholy/ProgressMeter.jl/pull/197#issuecomment-834723640

```
using ProgressMeter
n = 100
p = Progress(n)
for i in 1:n
    j = 1
    for j in 1:10
        next!(p, step=0, showvalues = [(:i, i), (:j, j)])
        sleep(1)
    end
    next!(p, showvalues = [(:i, i), (:j, j)])
end
```
Results in no output in 1.6.1. 

The predictor should be overriden for `step=0` updates. PR incoming

**Comment by vancleve** [comment]
oh great, sorry about not adding the MWE. This one captures the problem exactly!
