### ISSUE TITLE
ProgressUnknown display garbled when counter gets more digits

### ISSUE THREAD

**Issue by stevengj** [timholy/ProgressMeter.jl#208]
It seems like the `ProgressUnknown` display is sometimes broken when the number of digits in the counter increases.

For example:
```jl
using ProgressMeter
prog = ProgressUnknown("Working:")
while true
    ProgressMeter.next!(prog)
    rand(1:2*10^8) == 1 && break
end
ProgressMeter.finish!(prog)
```
outputs
```
Working: 263805411 me: 0 Time: 0:00:13
```
It doesn't always happen — e.g. running the code above a second time gives
```
Working: 93336116        Time: 0:00:04
```
which looks okay.

**Comment by MarcMush** [comment]
fixed by #274
