### ISSUE TITLE
`enabled = false` not working in IJulia

### ISSUE THREAD

**Issue by saulpila** [timholy/ProgressMeter.jl#214]
I am setting `enabled = false` but I still get a progress meter. Shouldn't it be `|` instead of `&` here?
https://github.com/timholy/ProgressMeter.jl/blob/e1c7c7127848ee270b6770e03971d326afad2b85/src/ProgressMeter.jl#L261
https://github.com/timholy/ProgressMeter.jl/blob/e1c7c7127848ee270b6770e03971d326afad2b85/src/ProgressMeter.jl#L339

**Comment by IanButterworth** [comment]
@jd-lara would you be able to take a look at this? On reflection, it's not clear to me what the behavior in IJulia (which I assume @saulpila is using) is supposed to be here

**Comment by saulpila** [comment]
Yes! This happens in IJulia. Sorry for not specifying.

**Comment by jd-lara** [comment]
@IanButterworth I can check it out but I don't use IJulia too much
