### ISSUE TITLE
Support multidimensional for loops

### ISSUE THREAD

**Issue by dhoegh** [timholy/ProgressMeter.jl#23]
It would be convenient if ProgressMeter supported multidimensional for loops like:
```
@showprogress for i=1:10, j=1:10
    sleep(0.1)
end
```

**Comment by garrison** [comment]
Good idea, and one I hadn't thought of.  (This an example of why it would be nice if Julia's AST were [documented](https://github.com/JuliaLang/julia/issues/10413).)

**Comment by garrison** [comment]
In order to work generally for things like `i=1:10, j=i:10`, I guess we need to run the loop twice: the first to simply count how many iterations; the second to do the actual work in the body of the loop.

**Comment by dhoegh** [comment]
Couldn't it just look at the value of the first index ´i´ so it would be equivalent to writing
 ´´´
for i=1:10
     for j=1:10
        sleep(0.1)
    end
end
´´´

**Comment by garrison** [comment]
Yes, it could.  Perhaps that is the best plan of action.  Thanks for pointing it out.

**Comment by timholy** [comment]
That's certainly the safest option. If people want something more accurate, they can always compute the length manually and use `next!`.

**Comment by garrison** [comment]
Once issue: doing the transformation you suggest would change the meaning of `break` inside the for loop.

**Comment by timholy** [comment]
Good catch. That's a dealbreaker.

I'd say, it would be fine to support this if the bounds of the loop can be inferred from the expression, and otherwise throw an error.

**Comment by dhoegh** [comment]
I hadn't thought about that, but couldn't it be left as a multidimensional for loop but only using the first index for the progress status? By the way, nice work with the package.

**Comment by garrison** [comment]
I'm not sure if it's possible; right now the macro puts `next!` at the end of the body of the for loop and immediately before any `continue` statements.

**Comment by garrison** [comment]
I guess an alternative implementation would be to have the iterable object itself be replaced by a wrapper that updates the counter as it is iterated.

**Comment by timholy** [comment]
But I still don't see how you reliably know when you'll quit. Unless, as you say, you run the loop twice and count up the first time. Can one guarantee that just running through the loop will be effect-free?

**Comment by garrison** [comment]
To be clear on the alternative implementation I am proposing, the line

    for i=1:10, j=i:10

could be transformed to

    meter = ProgressMeter(options...)
    for i=ProgressWrapper(1:10, meter), j=i:10

where the `ProgressWrapper` object implements its own `start`, `done`, `next`, and `length` methods.  The `next` method, in particular, would call `next!` on the `meter`.  We would no longer need to special handle `continue` statements, but would still want to handle `break`.

**Comment by timholy** [comment]
That sounds quite reasonable to me.

**Comment by garrison** [comment]
I managed to code up the alternative implementation and will open a pull request some time soon.

**Comment by timholy** [comment]
Sounds awesome, looking forward to seeing it.
