### ISSUE TITLE
It shows repeated output in VScode

### ISSUE THREAD

**Issue by albertomercurio** [timholy/ProgressMeter.jl#231]
Hello,

if I try to run the following script, it shows a repeated output.

```julia
p = Progress(10)
for i in 1:10
    sleep(0.5)
    next!(p)
end
```

```
Progress:  20%|████████▎                                |  ETA: 0:00:04
Progress:  30%|████████████▎                            |  ETA: 0:00:04
Progress:  40%|████████████████▍                        |  ETA: 0:00:03
Progress:  50%|████████████████████▌                    |  ETA: 0:00:03
Progress:  60%|████████████████████████▋                |  ETA: 0:00:02
Progress:  70%|████████████████████████████▊            |  ETA: 0:00:02
Progress:  80%|████████████████████████████████▊        |  ETA: 0:00:01
Progress:  90%|████████████████████████████████████▉    |  ETA: 0:00:01
Progress: 100%|█████████████████████████████████████████| Time: 0:00:05
```

**Comment by fpartl** [comment]
Hello, I have the same issue. 
![obrazek](https://user-images.githubusercontent.com/22639820/160454938-ba3aefee-454a-434c-a001-07ca77d11915.png)

**Comment by oschulz** [comment]
Just ran into this as well. :-)

**Comment by timholy** [comment]
I'd merge a PR that fixes it, if you care to submit one.

**Comment by oschulz** [comment]
No idea why this happens, but I can play around a bit.

**Comment by mofeing** [comment]
There is an open issue about this in https://github.com/microsoft/vscode-jupyter/issues/11837. Apparently there was a similar bug in Python https://github.com/microsoft/vscode/issues/146397.

**Comment by BenjaminDoran** [comment]
Issue seems to be dependent on which kernel is selected. i.e. using a jupyter kernel (that loads IJulia) works. using the default kernel from the julia vscode extension doesn't. 

some of this is from the `CLEAR_IJULIA[]` checking `isdefined(Main, :IJulia) && Main.IJulia.inited`

We can check if we are in the default vscode notebook context with:
```
# true if in vscode notebook
running_vscode_kernel() = isdefined(Main, :VSCodeServer) && !isinteractive() 
```
but I don't know of how to flush clear the output cell, when IJulia is not loaded

**Comment by affans** [comment]
Has there been any update to this? A manual fix for now or an alternative? I am using the default vscode extension kernel.

**Comment by MarcMush** [comment]
an equivalent to `IJulia.clear_output()` would be needed (https://github.com/julia-vscode/julia-vscode/issues/2473)

**Comment by oschulz** [comment]
How do Python VS-Code notebooks handle such things?

**Comment by oameye** [comment]
> Issue seems to be dependent on which kernel is selected. i.e. using a jupyter kernel (that loads IJulia) works. using the default kernel from the julia vscode extension doesn't.

I can confirm this

**Comment by davidanthoff** [comment]
I just released a new version of the extension that should improve the situation a bit. At least for simple one-line progress bar I think it should all work now.

**Comment by oameye** [comment]
I think this can be closed. It works for me in julia v1.11, ProgressMeter v1.10.0 and julia-vscode v1.90.1.
