### ISSUE TITLE
Extra characters displayed in progress meter

### ISSUE THREAD

**Issue by jangevaa** [timholy/ProgressMeter.jl#24]
Hello,
First, thank you for your excellent work with this package!

In my progress meter, a portion of the ANSI escape sequences are being displayed in the console. Such that they look like this:

`[1GYear 1 simulation progress 31%|███████████████                                   |  ETA: 0:17:47[K`

I am using Juno, and I suspect this may be an issue with how Juno handles these sequences and not an issue with your package. Can you offer any insight? Thank you!

**Comment by timholy** [comment]
They don't show up for me in the REPL, perhaps you could test that? Also roping in @one-more-minute in case he has any insights.

**Comment by one-more-minute** [comment]
Yeah, Juno's console is completely dumb – it just dumps all of Julia's STDOUT without handling control codes at all. So this isn't something that could reasonably be handled within ProgressMeter.jl.

**Comment by jangevaa** [comment]
Gotcha! Thanks for the explanation @one-more-minute
