### ISSUE TITLE
Docs suggestion: @showprogress Inf

### ISSUE THREAD

**Issue by fredcallaway** [timholy/ProgressMeter.jl#254]
I often want to add the option to conditionally disable a progressbar I've defined with `@showprogress`. Previously I would always switch to progress_map and use the enabled key word, but it just occurred to me that you can accomplish this much more easily by setting the dt parameter to Inf, e.g. `@showprogress Inf map(func, args)`. Might be worth adding this as an example in the docs for other users... or maybe this is obvious and I'm just really slow :P

**Comment by MarcMush** [comment]
This will be possible with the `enabled` kwarg with #275 

```julia
@showprogress enabled=false map(func, args)
```
