### ISSUE TITLE
ProgressMeter missing in 0.4?

### ISSUE THREAD

**Issue by cstjean** [timholy/ProgressMeter.jl#28]
I liked ProgressMeter a lot in 0.3, but now that I've switched,
```
julia> Pkg.add("ProgressMeter.jl")
ERROR: unknown package ProgressMeter.jl
 in error at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 [inlined code] from pkg/entry.jl:49
 in anonymous at task.jl:447
```
I've Pkg.updated, and all of the other packages work fine (ProfileView, Images, Gadfly, etc.)

**Comment by garrison** [comment]
Try the following:

    Pkg.add("ProgressMeter")

i.e. remove the `.jl`.  Please comment/reopen if this still does not work for you.

**Comment by cstjean** [comment]
Thank you, I should have caught that.

**Comment by garrison** [comment]
no problem :)
