### ISSUE TITLE
Is there a way to place progress bar always at the bottom?

### ISSUE THREAD

**Issue by jpmvferreira** [timholy/ProgressMeter.jl#280]
I would like to ask if there is a way to ensure that the progress bar would be located always at the end of the text, even if some output is being printed to the terminal.

To provide a visual example, I wanted my progress bar to look something like this
![image](https://github.com/timholy/ProgressMeter.jl/assets/41581666/21b16266-3516-440e-9ff5-c9d8bee0fb9c)
Where you can see the progress at the bottom of the terminal (or at the end of the text, would work either way) and if anything is printed to STDOUT/STDERR, it would not be cluttered by outdated versions of the progress bar, i.e.
![image](https://github.com/timholy/ProgressMeter.jl/assets/41581666/a969677a-7c51-4d44-bd73-a2e50cf7a558)

I would also to state that, once I add the `showvalues` optional argument in `next!`, all of my printing is gone as the output is cleared to ensure that the progress bar remains in-place.

**Comment by MarcMush** [comment]
Using `offset=1` and clearing manually lines with `"\u1b[K"`:

```julia
using ProgressMeter
p = Progress(50; offset=1)

for i in 1:50
   for _ in 1:rand(0:2)
       println(i, "\u1b[K")
   end
   print("\u1b[K")
   next!(p; showvalues=("i"=>i,))
   sleep(0.11)
end
```

It doesn't work in a notebook though, since offsets are broken with IJulia (#238)

**Comment by jpmvferreira** [comment]
Amazing, this is just what I wanted, many thanks!
