### ISSUE TITLE
`enabled=false` only suppresses output, still has overhead

### ISSUE THREAD

**Issue by Socob** [timholy/ProgressMeter.jl#312]
Using `@showprogress enabled=false` suppresses output from being printed, but any overhead from updating the `Progress` object is still there (see e. g. `progress_map()`). I think `enabled=false` should make `@showprogress` a no-op instead, since anything beyond that is just wasted time!

**Comment by MarcMush** [comment]
performance has drastically improved with #325, you can open the issue again with a MWE if the overhead still is too high for your usecase
