### ISSUE TITLE
Some tests did not pass

### ISSUE THREAD

**Issue by iajzenszmi** [timholy/ProgressMeter.jl#313]
![Screenshot from 2024-05-04 13-48-11](https://github.com/timholy/ProgressMeter.jl/assets/5051767/5b89a4db-4fd3-432e-973c-6600043e10f0)
![image](https://github.com/timholy/ProgressMeter.jl/assets/5051767/504f25c2-c8cd-48ec-ada2-57b11eba3e18)
![Screenshot from 2024-05-04 13-48-11](https://github.com/timholy/ProgressMeter.jl/assets/5051767/085d9238-1001-4f65-9f5e-120d0be860de)
now 0.01: Time: 0:00:06 (101 iterations)
Testing rounding (#300)
Progress: 100%|██████████████████████████| Time: 0:00:06
  percentage:  100.0
Test Summary: | Pass  Fail  Total     Time
Core          |  102     1    103  2m48.1s
ERROR: LoadError: Some tests did not pass: 102 passed, 1 failed, 0 errored, 0 broken.
in expression starting at /home/ian/.julia/packages/ProgressMeter/dMfiC/test/runtests.jl:9
ERROR: Package ProgressMeter errored during testing

**Comment by MarcMush** [comment]
What test is failing? Is it the performance test? It is not very reliable (#219)

**Comment by iajzenszmi** [comment]
![Screenshot from 2024-05-04 21-28-57](https://github.com/timholy/ProgressMeter.jl/assets/5051767/6f1ffa3b-38f4-44f6-9bf3-08c827a4600c)

**Comment by MarcMush** [comment]
That's an annoying one, the number 9 chosen is arbitrary for deciding what performance hit is acceptable
It never passes on my reasonably performant and recent windows machine

**Comment by MarcMush** [comment]
However 9s seem very long so there might be a problem somewhere

**Comment by MarcMush** [comment]
closed in favour of #323
