### ISSUE TITLE
Working with pmap

### ISSUE THREAD

**Issue by slundberg** [timholy/ProgressMeter.jl#32]
I thought I should note here that I found working with pmap and ProgressMeter a bit tricky, so I bundled the solution as a very simple package: https://github.com/slundberg/PmapProgressMeter.jl which provides `pmap(p::Progress, f::Function, values)`.

This is related to #9 and it may be of interest to eventually merge this into ProgressMeter.

**Comment by timholy** [comment]
Seems like a good thing to me. Want to prepare a PR? Alternatively, we could add a link to your package from the README. (But I'd say it's reasonable to have this functionality in ProgressMeter itself, if you agree.)

**Comment by timholy** [comment]
Hmm, though see also #31 for related discussion. `map` is a lot more complex to support, but I guess it's debatable whether we'd want `pmap` but omit `map`. Soliciting thoughts.

**Comment by garrison** [comment]
> Soliciting thoughts.

I don't have a strong opinion here.

But I do think `pmap` (as implemented in PmapProgressMeter.jl) should take the `Progress` meter as its second argument, not its first argument as it currently does.  With this change, it will again be possible to use julia's `do` block syntax with it.

**Comment by slundberg** [comment]
I am happy to submit a PR (and good point about the argument order). Just let me know if you think it would be beneficial.

**Comment by dgleich** [comment]
Any update on this pull request? Would love to get this functionality!

**Comment by tlnagy** [comment]
Same here. Bump.

**Comment by timholy** [comment]
I'm willing to go for pmap and not tackle map.

**Comment by tlnagy** [comment]
I would be happy with pmap first!
 
 
On Thu, May 26, 2016, at 20:44, Tim Holy wrote:
> I'm willing to go for pmap and not tackle map.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>

Links:

  1. https://github.com/timholy/ProgressMeter.jl/issues/32#issuecomment-222053394
  2. https://github.com/notifications/unsubscribe/ABlaL0nwbpKy5o6Pe7ZtcW8MO4uM-YB8ks5qFmiDgaJpZM4Gc5Lu

**Comment by kkmann** [comment]
+1

**Comment by djsegal** [comment]
Any word on this?

**Comment by zsunberg** [comment]
I noticed that `Distributed.pmap` has keyword arguments *and* an optional `AbstractWorkerPool` positional argument. I think giving it a `Progress` positional argument in addition might make things too confusing.

I see four additional options:

1. Use a keword argument: `pmap(args...; progress::Progress, kwargs...)`
  The problem with this is that I don't know how to dispatch it properly.
2. Have people explicitly use `ProgressMeter.pmap(args...; progress::Progress, kwargs...)` if they want the progress meter and don't import Distributed.pmap.
3. Create a new function `progress_pmap(args...; progress::Progress, kwargs...)`
4. Use a macro `@showprogress pmap(...)`
  This is probably most convenient/least confusing to users, but also the most difficult to implement.

I guess 4 is the best. Does anyone have any other thoughts?

(perhaps @showprogress should be implemented by doing 2 or 3 and then just changing the call to that)
