### ISSUE TITLE
Allow to update the description

### ISSUE THREAD

**Issue by alyst** [timholy/ProgressMeter.jl#33]
It would be nice, if ProgressMeter can support updating the description line during the task execution, e.g. to monitor the current minimal value during function optimization.

**Comment by tlycken** [comment]
I like the idea, but I have no idea what the API for it should be like. @alyst, do you have any suggestions?

**Comment by alyst** [comment]
IMO if `update!()` could be extended to take `desc::AbstractString` argument, it would be quite convenient. Actually, `color` argument is more exotic to my taste than `desc`, so for this new method I would keep `color` at the last position.

**Comment by garrison** [comment]
Instead of choosing an arbitrary order, perhaps `color` and `desc` should both be keyword arguments to `update!`?  We could then deprecate the existing three-argument function where `color` is provided in the third position.

**Comment by alyst** [comment]
@garrison Given that we don't really need the dispatch to be dependent on these parameters, I think it's the best solution. Perhaps, progress bar constructors and `cancel()` method should also be updated for consistency.

**Comment by timholy** [comment]
@alyst, if you want to try tackling this, see http://docs.julialang.org/en/stable/manual/packages/#package-development
