### ISSUE TITLE
Nested progress bars

### ISSUE THREAD

**Issue by juliohm** [timholy/ProgressMeter.jl#52]
Is it possible to produce nested progress bars as in a big task composed of smaller tasks?

**Comment by grero** [comment]
I would also be interested in this ability.

**Comment by juliohm** [comment]
Issue #42 is related, I am not sure about making it a plot, but I like the visual with multiple bars stacked as an initial implementation.

**Comment by juliohm** [comment]
It seems that the feature was implemented by @IsaacTay in #113. Could you please to documentation? Do we have documentation in the README?

**Comment by bhvieira** [comment]
Not sure about docs, just stumbled upon the project, but see the examples added with that PR @juliohm 

Here's (an adapted) one:
```
ProgressMeter.@showprogress "Level 0 " for i in 1:10
        ProgressMeter.@showprogress " Level 1 " 1 for i2 in 1:10
            ProgressMeter.@showprogress "  Level 2 " 2 for i3 in 1:10
                sleep(0.5)
            end
        end
end
```

**Comment by juliohm** [comment]
Thank you @bhvieira , marking the issue as solved then. :+1:
