### ISSUE TITLE
Cursor disappears after using `showvalues`

### ISSUE THREAD

**Issue by ahwillia** [timholy/ProgressMeter.jl#54]
I was looking to add this to the README as an example for the `showvalues` functionality:

```julia

x,n = 1,10
p = Progress(n)
for iter = 1:10
    x *= 2
    sleep(0.5)
    ProgressMeter.next!(p; showvalues = [(:iter,iter), (:x,x)])
end
```

Upon doing this, I realized that my cursor in the REPL was gone!

<img width="513" alt="screen shot 2016-08-10 at 12 06 21 am" src="https://cloud.githubusercontent.com/assets/636625/17544843/89210d6e-5e8e-11e6-8a92-e70f1c64ded9.png">

For reference, this is what it looks like when I run the same loop, but don't use `showvalues`:

<img width="508" alt="screen shot 2016-08-10 at 12 09 13 am" src="https://cloud.githubusercontent.com/assets/636625/17544863/b29ff0b0-5e8e-11e6-84b9-a21cff6e9520.png">

I believe I see this on both v0.5 and v0.4 -- I'm using the basic Terminal app on a Mac if that is important.

cc @robertfeldt

**Comment by robertfeldt** [comment]
Good catch, I will take a look. Haven't noticed this before but I run iTerm so might be related.

**Comment by robertfeldt** [comment]
Yes, I actually found the line:

```julia
print(p.output, "\u1b[?25l") # Hide cursor
```

in the source which I probably added since I thought it looked a bit weird keeping the cursor around. But if showvalues is not used the cursor is actually not hidden. So maybe just delete that line? Alternatively we can just be sure to show the cursor again after we are ready but that might not work if it was hidden before the iteration started?

**Comment by robertfeldt** [comment]
BTW, the way to show the cursor again if we decide to take that route should be:

```julia
print(p.output, "\u1b[?25h")
```

**Comment by ahwillia** [comment]
Either fix seems fine to me.

**Comment by robertfeldt** [comment]
If you or @timholy want me to do a PR I can do it but it is just about deleting that one line so would be great if one of you can do it, thanks.

**Comment by ahwillia** [comment]
K I can do it.

**Comment by ahwillia** [comment]
Oh - my fault this seems to be already fixed on the latest master! @timholy - can we tag another release for this?

**Comment by timholy** [comment]
Done.
