### ISSUE TITLE
Working with `@parallel`

### ISSUE THREAD

**Issue by adamslc** [timholy/ProgressMeter.jl#59]
I've written up a small package ([ParallelProgressMeter.jl](https://github.com/adamslc/ParallelProgressMeter.jl)) for using progress meters with the `@parallel` macro. It currently uses the slightly clunky syntax `@parallelprogress`, but I think the original `@showprogress` macro could be rewritten to incorporate the changes as well.

I should note that most of the inspiration came from [PmapProgressMeter.jl](https://github.com/slundberg/PmapProgressMeter.jl).

**Comment by juliohm** [comment]
Why not contribute instead of creating 2 different forks?

**Comment by juliohm** [comment]
Can you please close this issue? This is not the place to announce another package.
