### ISSUE TITLE
STDOUT by default?

### ISSUE THREAD

**Issue by RedPointyJackson** [timholy/ProgressMeter.jl#60]
Why does this package uses `STDOUT` by default? It can be very cumbersome to manually redirect every progress bar if one wants to pipe the output of a program to a file.

**Comment by alexmorley** [comment]
Seems to me like this would be a decent default as the most common use case for a progress bar would be displaying the output on STDOUT?

**Comment by RedPointyJackson** [comment]
Why on STDOUT? For example, `wget` shows progress in STDERR, like `curl`. The only applications that use STDOUT are the ones not designed to be piped, which is very limiting for a general purpose language like Julia. 

Also, displaying the bar in STDERR has no effect whatsoever for people who does not intend to redirect the output, and is very convenient to people who does.

**Comment by alexmorley** [comment]
For sure, I didn't realise that was the alternative you were proposing.

**Comment by RedPointyJackson** [comment]
Oh, sorry, I should have been more clear in the issue.

**Comment by timholy** [comment]
Want to submit a PR to change it?

**Comment by timholy** [comment]
Closed by #64
