### ISSUE TITLE
Simulations that are longer than a day

### ISSUE THREAD

**Issue by juliohm** [timholy/ProgressMeter.jl#61]
The counter restarts after a day has passed apparently. This is a feature request for adding days as the maximum unit of time if the simulation takes longer than a day.

**Comment by mauro3** [comment]
Mine can do it:
`Progress:   9%|████                                     |  ETA: 2 days, 7:01:58`

**Comment by juliohm** [comment]
Interesting, maybe it is working with some recent change? I will close the issue and reopen if necessary.
