### ISSUE TITLE
Progress bar broken into multiple pieces

### ISSUE THREAD

**Issue by juliohm** [timholy/ProgressMeter.jl#62]
Every now and then the progress bar is broken into pieces as in the screenshot below:

![screenshot from 2016-12-20 20-24-53](https://cloud.githubusercontent.com/assets/3345261/21372061/daac3bfe-c6f3-11e6-94b7-cdbd07b9a0c3.png)

What can be done to solve this (flush) issue?

**Comment by juliohm** [comment]
At a larger scale, this is how it looks like:

![screenshot from 2016-12-20 20-40-39](https://cloud.githubusercontent.com/assets/3345261/21372226/ad7c781e-c6f4-11e6-80b0-f4bf3bad5d2e.png)

**Comment by juliohm** [comment]
I will close this issue, but every now and then we get some odd behavior on Jupyter.

**Comment by timholy** [comment]
The key will be to find a way to make it reproducible; until then, it's hopeless to try to fix it.
