### ISSUE TITLE
Add disable flag to @showprogress to flag on/off

### ISSUE THREAD

**Issue by djsegal** [timholy/ProgressMeter.jl#70]
Sometimes you want the progress bar, sometimes you don't

Maybe add verbose flag to `@showprogress` to allow dynamic usage

**Comment by timholy** [comment]
I'm not certain I fully understand what you're asking for here, can you be more explicit? Also, have you run the tests locally? They do a nice job of illustrating the diversity of printing options.

**Comment by djsegal** [comment]
I'll look into the tests

---------

What I meant is something like this:

```
function foo(bar; verbose=false)
  do_show_progress = !verbose
  wait_time = do_show_progress ? 1 : 0

  @showprogress wait_time "Computing..." for i in 1:50
      sleep(0.1)
  end
end
```

// right now a `wait_time` of `0` just updates every `ms` or something

**Comment by timholy** [comment]
Try changing that to `wait_time = verbose ? 1 : Inf`.

**Comment by MarcMush** [comment]
the `enabled` keyword can disable a progress bar (documented in the readme)
