### ISSUE TITLE
Progress bar stops after a while in Jupyter notebooks

### ISSUE THREAD

**Issue by juliohm** [timholy/ProgressMeter.jl#76]
When the task is too long, Jupyter stops the progress bar with the message:

>Excessive output truncated after 524411 bytes.

According to https://github.com/JuliaLang/IJulia.jl/issues/455#issuecomment-322462631, we need to reset `IJulia.stdio_bytes[] = 0` after a while.

Where should this reset happen in the source code?

**Comment by stevengj** [comment]
Probably in the [printover function](https://github.com/timholy/ProgressMeter.jl/blob/413d2cc02601e7bf5e0526caf4afab17154e9490/src/ProgressMeter.jl#L302-L310)?

This function might be worth revisiting anyway, since nowadays IJulia supports ANSI color codes.

**Comment by juliohm** [comment]
@stevengj you are the expert in Jupyter/IJulia, could you maybe submit a PR with these updated features? :blush:
