### ISSUE TITLE
showvalues option does not work in IJulia

### ISSUE THREAD

**Issue by juliohm** [timholy/ProgressMeter.jl#85]
```
using ProgressMeter

p = Progress(100)

for i=1:100
    sleep(1)
    next!(p, showvalues=[(:i,i)])
end
```

It keeps adding lines vertically instead of overwriting the existing line.

**Comment by Paethon** [comment]
No idea if this has been fixed by now, but for me this works as expected.

**Comment by Paethon** [comment]
I think this is the same as issue #71

**Comment by juliohm** [comment]
Thank you @Paethon , it must be the same issue indeed. Closing this one.
